# Generated by Django 5.1.6 on 2025-02-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(help_text='Уникальный идентификатор клиента', max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('cold', 'Cold'), ('new', 'New'), ('regular', 'Regular'), ('loyal', 'Loyal'), ('lost', 'Lost')], help_text='Текущий статус клиента', max_length=10)),
                ('status_change', models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], help_text='Направление изменения статуса', max_length=10, null=True)),
                ('average_interval', models.FloatField(default=0, help_text='Средний интервал между заказами в днях')),
                ('days_since_last_order', models.IntegerField(default=0, help_text='Дней с последнего заказа')),
                ('orders_count', models.IntegerField(default=0, help_text='Количество заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='StatusSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_settings', models.JSONField(default=dict, help_text='Ручные настройки для определения статусов')),
                ('use_auto_calculation', models.BooleanField(default=False, help_text='Использовать автоматический расчет статусов')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Status Settings',
                'verbose_name_plural': 'Status Settings',
                'db_table': 'status_settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(help_text='Уникальный идентификатор заказа', max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(help_text='Дата и время заказа')),
                ('total', models.DecimalField(decimal_places=2, help_text='Общая сумма заказа', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('client', models.ForeignKey(help_text='Клиент, сделавший заказ', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(help_text='Уникальный идентификатор позиции заказа', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование товара', max_length=255)),
                ('quantity', models.IntegerField(help_text='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за единицу', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Общая стоимость позиции', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('order', models.ForeignKey(help_text='Заказ, к которому относится позиция', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
    ]
